import 'dart:ui' as ui;

/// A wrapper over the image used to control the blur distribution.
///
/// It allows to distinguish between an image provided by the user
/// via Inspire Blur public API, and one generated internally, in order
/// to manage the lifecycle of the image instance accordingly.
class BlurDistributionImage {
  final ui.Image image;
  final bool _owned;

  /// A wrapped [image] which was generated by the Inspire Blur library
  /// and **should be** disposed internally.
  BlurDistributionImage.owned(this.image) : _owned = true;

  /// A wrapped [image] which was passed by the user via public API
  /// and **should not be** disposed internally.
  BlurDistributionImage.borrowed(this.image) : _owned = false;

  /// Disposes the image when it's no longer used, to free the resources.
  void dispose() {
    if (_owned) image.dispose();
  }
}
